name: Modify Framework

on:
  workflow_dispatch:
    inputs:
      framework_jar_url:
        description: 'URL to download framework.jar'
        required: true
        default: 'https://dumps.tadiphone.dev/dumps/redmi/xaga/-/raw/missi_phone_cn-user-14-UP1A.231005.007-V816.0.1.0.ULOCNXM-release-keys/system/system/framework/framework.jar'
      android_api_level:
        description: 'Android API level'
        required: true
        default: '34'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install -y default-jdk zipalign 7zip python3

    - name: Download framework.jar
      run: |
        curl -L -o framework.jar "${{ github.event.inputs.framework_jar_url }}"

    - name: Clone smali repository
      run: git clone --depth=1 https://github.com/JesusFreke/smali.git

    - name: Build smali and baksmali
      run: |
        cd smali
        ./gradlew build

    - name: Extract framework.jar
      run: 7z x framework.jar -oframework

    - name: Decompile dex files
      run: |
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes.dex -o classes
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes2.dex -o classes2
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes3.dex -o classes3

    - name: List decompiled files for debugging
      run: |
        echo "Contents of classes directory:"
        find classes
        echo "Contents of classes2 directory:"
        find classes2
        echo "Contents of classes3 directory:"
        find classes3

    - name: Backup smali files
      run: |
        cp -r classes classes_backup
        cp -r classes2 classes2_backup
        cp -r classes3 classes3_backup

    - name: Modify smali files
      run: |
        python3 patch.py

    - name: Recompile dex files
      run: |
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes -o framework/classes.dex
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes2 -o framework/classes2.dex
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes3 -o framework/classes3.dex

    - name: Recompile framework.jar
      run: 7z a -tzip framework_new.zip framework/*

    - name: Align the zip
      run: zipalign -f -p -v -z 4 framework_new.zip aligned_framework.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aligned_framework
        path: aligned_framework.jar
