name: Modify Framework

on:
  workflow_dispatch:
    inputs:
      framework_jar_url:
        description: 'URL to download framework.jar'
        required: true
        default: 'https://dumps.tadiphone.dev/dumps/redmi/xaga/-/raw/missi_phone_cn-user-14-UP1A.231005.007-V816.0.1.0.ULOCNXM-release-keys/system/system/framework/framework.jar'
      android_api_level:
        description: 'Android API level'
        required: true
        default: '34'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'termurin'
        java-version: '21'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install -y default-jdk zipalign 7zip

    - name: Download framework.jar
      run: |
        curl -L -o framework.jar "${{ github.event.inputs.framework_jar_url }}"

    - name: Clone smali repository
      run: git clone --depth=1 https://github.com/JesusFreke/smali.git

    - name: Build smali and baksmali
      run: |
        cd smali
        ./gradlew build

    - name: Extract framework.jar
      run: 7z x framework.jar -oframework

    - name: Decompile dex files
      run: |
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes.dex -o classes
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes2.dex -o classes2
        java -jar smali/baksmali/build/libs/baksmali.jar d -a ${{ github.event.inputs.android_api_level }} framework/classes3.dex -o classes3

    - name: List decompiled files for debugging
      run: |
        echo "Contents of classes directory:"
        find classes
        echo "Contents of classes2 directory:"
        find classes2
        echo "Contents of classes3 directory:"
        find classes3

    - name: Backup smali files
      run: |
        cp -r classes classes_backup
        cp -r classes2 classes2_backup
        cp -r classes3 classes3_backup

    - name: Modify smali files
      run: |
        directories=("classes" "classes2" "classes3")

        for dir in "${directories[@]}"; do
          signing_details="$dir/android/content/pm/SigningDetails.smali"
          package_parser_signing_details="$dir/android/content/pm/PackageParser\$SigningDetails.smali"

          # Modify checkCapability methods in SigningDetails.smali
          if [ -f "$signing_details" ]; then
            awk '
            /method.*checkCapability(Landroid\/content\/pm\/SigningDetails;I)Z/ {
              print ".method public checkCapability(Landroid/content/pm/SigningDetails;I)Z\n    .registers 4\n\n    const/4 v0, 0x1\n\n    return v0\n.end method"
              next
            }
            /method.*checkCapability(Ljava\/lang\/String;I)Z/ {
              print ".method public checkCapability(Ljava/lang/String;I)Z\n    .registers 4\n\n    const/4 v0, 0x1\n\n    return v0\n.end method"
              next
            }
            /method.*checkCapabilityRecover(Landroid\/content\/pm\/SigningDetails;I)Z/ {
              print ".method public checkCapabilityRecover(Landroid/content/pm/SigningDetails;I)Z\n    .registers 4\n    .annotation system Ldalvik/annotation/Throws;\n        value = {\n            Ljava/security/cert/CertificateException;\n        }\n    .end annotation\n\n    const/4 v0, 0x1\n\n    return v0\n.end method"
              next
            }
            { print }
            ' "$signing_details" > "${signing_details}.tmp" && mv "${signing_details}.tmp" "$signing_details"
            echo "Modified checkCapability methods in SigningDetails.smali in $dir"
          else
            echo "SigningDetails.smali not found in $dir!"
          fi

          # Modify hasAncestorOrSelf method in PackageParser$SigningDetails.smali
          if [ -f "$package_parser_signing_details" ]; then
            awk '
            /method.*hasAncestorOrSelf(Landroid\/content\/pm\/PackageParser\$SigningDetails;)Z/ {
              print ".method public greylist-max-o hasAncestorOrSelf(Landroid/content/pm/PackageParser\$SigningDetails;)Z\n    .registers 6\n\n    const/4 v0, 0x1\n\n    return v0\n.end method"
              next
            }
            { print }
            ' "$package_parser_signing_details" > "${package_parser_signing_details}.tmp" && mv "${package_parser_signing_details}.tmp" "$package_parser_signing_details"
            echo "Modified hasAncestorOrSelf method in PackageParser\$SigningDetails.smali in $dir"
          else
            echo "PackageParser\$SigningDetails.smali not found in $dir!"
          fi
        done

    - name: Recompile dex files
      run: |
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes -o framework/classes.dex
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes2 -o framework/classes2.dex
        java -jar smali/smali/build/libs/smali.jar a -a ${{ github.event.inputs.android_api_level }} classes3 -o framework/classes3.dex

    - name: Recompile framework.jar
      run: 7z a -tzip framework_new.zip framework/*

    - name: Align the zip
      run: zipalign -f -p -v -z 4 framework_new.zip aligned_framework.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aligned_framework
        path: aligned_framework.jar
