name: Framework Patch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permission for the script
      run: chmod +x ./framework_patch.sh

    - name: Execute framework patch script
      run: ./framework_patch.sh

    - name: Upload modified framework.jar
      uses: actions/upload-artifact@v4
      with:
        name: modified-framework
        path: framework.jar
