name: Framework Patch

on:
  workflow_dispatch:
    inputs:
      framework_url:
        description: 'URL to download framework.jar'
        required: true
        type: string

jobs:
  patch-framework:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install -y default-jdk zipalign
        mkdir -p working_dir/framework
        cd working_dir

    - name: Download framework.jar
      run: |
        curl -L ${{ github.event.inputs.framework_url }} -o working_dir/framework.jar

    - name: Extract framework.jar
      run: |
        7z x working_dir/framework.jar -oworking_dir/framework

    - name: Decompile .dex files using baksmali
      run: |
        cd working_dir
        for dex in framework/*.dex; do
          java -jar ../baksmali.jar d -a 29 "$dex" -o "${dex%.dex}"
        done

    - name: Modify smali files
      run: |
        # Modify AndroidKeyStoreSpi.smali
        sed -i '/return-object v3/i \
        invoke-static {v3}, Lcom/android/internal/util/framework/Android;->engineGetCertificateChain([Ljava/security/cert/Certificate;)[Ljava/security/cert/Certificate;\
        move-result-object v3' working_dir/framework/classes3/android/security/keystore2/AndroidKeyStoreSpi.smali

        # Modify Instrumentation.smali
        sed -i '/return-void/i \
        invoke-static {p1}, Lcom/android/internal/util/framework/Android;->onNewApp(Landroid/content/Context;)V' working_dir/framework/classes/android/app/Instrumentation.smali

        # Modify ApplicationPackageManager.smali
        sed -i '/move-result v0/i \
        invoke-static {v0, p1}, Lcom/android/internal/util/framework/Android;->hasSystemFeature(ZLjava/lang/String;)Z\
        move-result v0' working_dir/framework/classes/android/app/ApplicationPackageManager.smali

    - name: Recompile .dex files using smali
      run: |
        cd working_dir
        for dir in classes*; do
          java -jar ../smali.jar a -a 29 "$dir" -o "framework/${dir##*/}.dex"
        done

    - name: Repackage framework.jar
      run: |
        cd working_dir/framework
        7z a -tzip -mx=0 ../framework.zip *
        zipalign -f -p -v -z 4 ../framework.zip ../framework.jar

    - name: Save modified framework.jar
      uses: actions/upload-artifact@v4
      with:
        name: modified-framework
        path: working_dir/framework.jar
